- name: Deploy Sentiment Analysis App
  hosts: localhost
  become: false
  tasks:

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      shell: docker pull imrds7/sentiment-analysis-app:latest

    - name: Run Docker Container
      shell: |
        docker run -d --name sentiment-analysis-app \
          -p 5000:5000 imrds7/sentiment-analysis-app:latest
